main: com.swiftpenguin.CrazyLoggerSP.CrazyLoggerSP
name: CrazyLoggerSP
version: 1.8
author: Cobwebster
depend: [CrazyCrates]

commands:
  crazylogger:
     description: lookup cmd
     usuage: /<command>

permissions:
    crazylogger.lookup:
        description: Allows lookup
        default: op
    crazylogger.exempt:
        description: Exempt from logging
        default: op